services:
  spectralshield:
    image: REPLACED_BY_CI # will be overridden by deploy script
    container_name: spectralshield_staging
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - ENV=staging
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 5

