name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Determine version
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LAST_TAG#v}"
          NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "new=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push images
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:${{ steps.version.outputs.new }}
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:${{ steps.version.outputs.sha }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:${{ steps.version.outputs.new }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:${{ steps.version.outputs.sha }}

    - name: Create Release and Upload Assets
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.new }}
        name: SpectralShield ${{ steps.version.outputs.new }}
        body: |
          ✅ Auto-built SpectralShield release

          Tags:
          • `latest`
          • `${{ steps.version.outputs.new }}`
          • `${{ steps.version.outputs.sha }}`
        files: |
          docker-compose.yml
          deploy.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_REPO_PAT }}

      - name: Upload docker-compose.yml as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_REPO_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docker-compose.yml
          asset_name: docker-compose.yml
          asset_content_type: text/plain
