name: Mirror & Deploy SpectralShield

on:
  repository_dispatch:
    types: [update-app]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout deploy repo
      uses: actions/checkout@v3
      
    - name: Clone latest app code
      run: |
        git clone https://github.com/cl00dz/spectralshield-code app
        cd app && git log -1

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest ./app

    - name: Push Docker image
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest

    - name: Copy SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Redeploy on Portainer Node
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem \
        ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
        cd /opt/spectralshield && \
        docker compose pull && \
        docker compose up -d \
        "
