name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      target_tag:
        description: "Image tag to promote (e.g., SHA12)"
        required: true

env:
  IMAGE_NAME: ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout deploy repo
      uses: actions/checkout@v4

    - name: Write SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to PROD (Portainer node)
      run: |
        ./scripts/deploy_remote.sh \
          --host "${{ secrets.SSH_HOST }}" \
          --user "${{ secrets.SSH_USER }}" \
          --key "key.pem" \
          --remote-dir "/opt/spectralshield" \
          --compose "deploy/docker-compose.prod.yml" \
          --image "$IMAGE_NAME:${{ inputs.target_tag }}"

