name: Release SpectralShield

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  build-docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract version tag
        id: get_version
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:${{ env.TAG }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:${{ env.TAG }}

  build-installer:
    name: Build Windows Installer
    needs: build-docker
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installers/windows/SpectralShield.iss"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            deploy.ps1
            docker-compose.yml
            installers/windows/SpectralShield-Installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_REPO_PAT }}
