name: 🚀 Release SpectralShield Offline

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cl00dz/spectralshield-deploy:latest
            ghcr.io/cl00dz/spectralshield-deploy:${{ env.TAG }}
            
      # Create offline bundle
      - name: Create release bundle
        run: |
          mkdir release-bundle
          cp docker-compose.yml release-bundle/
          cp run.ps1 release-bundle/
          cp run.sh release-bundle/
          cp README_RUN.txt release-bundle/
          cd release-bundle
          zip -r ../spectralshield-offline.zip .
          cd ..

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            spectralshield-offline.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
