name: Sync Code & Build Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "🚀 Starting sync and build"

      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          repository: cl00dz/spectralshield-deploy
          persist-credentials: false

      - name: Clone latest code repo
        run: |
          rm -rf temp_code
          git clone https://${{ secrets.CODE_REPO_PAT }}@github.com/cl00dz/spectralshield-code.git temp_code

      - name: Sync application files
        run: |
          mkdir -p app
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'Dockerfile' \
            --exclude 'docker-compose.yml' \
            --exclude 'README.md' \
            temp_code/ app/

      - name: Commit & Push updated app files
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@github"
          git add app/
          if git diff --cached --quiet; then
            echo "✅ No file changes to sync"
          else
            git commit -m "Sync from code repo"
            git remote set-url origin https://${{ secrets.DEPLOY_REPO_PAT }}@github.com/cl00dz/spectralshield-deploy.git
            git push origin main --force
            echo "✅ Deploy repo updated"
          fi

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/spectralshield:latest
          echo "✅ Docker image built & pushed to GHCR"
